spring.application.name=VersatileBackendPrototype
spring.data.mongodb.uri=${MONGODB_ENDPOINT}
server.port = 8085

qdrant.api.token=${QDRANT_API_TOKEN}
hf.api.token=${HF_API_TOKEN}
redis.endpoint=${REDIS_ENDPOINT}