spring.application.name=VersatileBackendPrototype
spring.data.mongodb.uri=${MONGODB_ENDPOINT}
server.port = 8085

qdrant.api.tokens=${QDRANT_API_TOKENS}
qdrant.cluster.urls=${QDRANT_CLUSTER_URLS}

hf.api.token=${HF_API_TOKEN}
hf.url=${HF_URL}

redis.endpoint=${REDIS_ENDPOINT}

rate.limit=${RATE_LIMIT}
user.rate.limit=${USER_RATE_LIMIT}