spring.application.name=VersatileBackendPrototype
spring.data.mongodb.uri=${MONGODB_ENDPOINT}
server.port = 8085

qdrant.api.tokens=${QDRANT_API_TOKENS}
qdrant.cluster.urls=${QDRANT_CLUSTER_URLS}

hf.api.token=${HF_API_TOKEN}
hf.url=${HF_URL}

redis.endpoint=${REDIS_ENDPOINT}

qdrant.write.rate.limit=${QDRANT_WRITE_RATE_LIMIT}
qdrant.read.rate.limit=${QDRANT_READ_RATE_LIMIT}

user.write.rate.limit=${USER_WRITE_RATE_LIMIT}
user.read.rate.limit=${USER_READ_RATE_LIMIT}

shards.amount=${SHARD_AMOUNT}

notifier.email=${NOTIFIER_EMAIL}
notifier.api.key=${NOTIFIER_API_KEY}